name: CI
on: push

jobs:
  jdk15:
    name: OpenJDK 15 (Ubuntu)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: AdoptOpenJDK/install-jdk@v1
        with:
          version: '15'
      - name: Gradle Build
        run: |
          ./gradlew --version --console=plain
          ./gradlew build -Psnapshot --info -S --console=plain